### ISSUE TITLE
Add a way to support re-estimation

### ISSUE THREAD

**Issue by manuellazzari-cargoone** [fpischedda/unrefined#28]
More a feature request than an issue report. There is apparently no way to support re-estimating a ticket.

**Comment by fpischedda** [comment]
Actually it is possible to re-estimate a ticket in case there is no clear winner:

- story points delta > 3
- a tie

I can enable it generally if you think it can be helpful; can you share the use case that you have in mind @manuellazzari-cargoone ?

**Comment by fpischedda** [comment]
Actually the button has been accidentally removed.

Enabled it again in #34 and the button has been added to the watch page because it can be handy there too.
