### ISSUE TITLE
Add user input validation, at least for the name field

### ISSUE THREAD

**Issue by fpischedda** [fpischedda/unrefined#31]
It is easy to forget to put the name of the voter and this makes looking at the results page a bit difficult, especially when a ticket needs to be rediscussed.

Enabling validation (even on the client side only) should avoid this problem.

**Comment by bognix** [comment]
on it 👍

**Comment by fpischedda** [comment]
Thanks a lot! :pray:

**Comment by fpischedda** [comment]
@bognix 

This the is template to work on https://github.com/fpischedda/unrefined/blob/main/resources/templates/estimate-view.html

**Comment by fpischedda** [comment]
Simple validator introduced here #39
