### ISSUE TITLE
Links created for async estimation are no more valid after 12h

### ISSUE THREAD

**Issue by manuellazzari-cargoone** [fpischedda/unrefined#32]
![Screenshot 2022-11-17 at 10 07 02](https://user-images.githubusercontent.com/105226274/202403642-30ba8d8e-9045-42da-8b33-975aa899505a.png)

https://unrefined.one/refine/HBQXPF/ticket/PE-12840/estimate
https://unrefined.one/refine/HBQXPF/ticket/PE-12843/estimate
https://unrefined.one/refine/HBQXPF/ticket/PE-12844/estimate
https://unrefined.one/refine/HBQXPF/ticket/PE-12846/estimate

**Comment by fpischedda** [comment]
@manuellazzari-cargoone Thanks for reporting!

This bug is pure genius! :rofl:

I have added the persistent storage for the permalink data BUT when trying to access it I first check in the volatile memory :man_facepalming:

Will be fixed in the next release.

**Comment by fpischedda** [comment]
@manuellazzari-cargoone 

It is fixed now so I am closing this issue.
